### ISSUE TITLE
Commissioning not effective with already commissioned machine

### ISSUE THREAD

**Issue by diyPresso** [diyPresso/diyPresso-One#11]
- Commissioning not effective with already commissioned machine
- software 1.6.0 test version
- what do you see: when commissioning a machine that already has water in the boiler the user cannot get past the first commissioning step and the display indicates:" Error no fill" 
- Effect: boiler full, but user cannot use the machine after software update
- Situation: commissioning a diyPresso One that is already commissioned.
- What did you expect: option for the user to indicate that the machine has been commissioned before then go to last step
- Possible solution: Ask the user to indicate if the machine has been commissioned before, if positive then go to last step after button click

**Comment by pbrier** [comment]
In the intial step, the weight was checked (it should be reduced when the boiler is filled) We now only check the weight in the last step (when water pours out): The total weight in the reservoir should be reduced.

Note: after a firmware upgrade, you should ALWAYS fill the reservoir to maximum capacity, as it is tared again
