### ISSUE TITLE
final step commissioning slightly confusing

### ISSUE THREAD

**Issue by diyPresso** [diyPresso/diyPresso-One#14]
- software 1.6.0 test version
- what do you see: : Last commissioning step confusing. " check water flow" 
- Effect: user doesn't know what to do
- Situation: after first startup after build or software update the machine starts the commissioning. the final step is for the user to indicate wheather water exits the brew head. In order to be sure the boiler is filled.
- What did you expect: " Do you see water exiting the brew head? Y/N" - " Press button"
- Possible solution: " Do you see water exiting the brew head? Y/N" - " Press button" if yes --> commissioning effective, if no go back to start commissioning

**Comment by bhulshof** [comment]
fixed thanks!
