### ISSUE TITLE
button not responsive during commissioning (small issue)

### ISSUE THREAD

**Issue by diyPresso** [diyPresso/diyPresso-One#15]
- software 1.6.0 test version
- what do you see: : have to push button multiple times before reaction
- Effect: user doesn't know what to do / confusion
- Situation: after first startup after build or software update the machine starts the commissioning. the user has to push the button to indicate that the water reservoir is filled (and at the end that there is water coming from the brew head). now the user has to push multiple times before the machine reacts.
- What did you expect: only one button press needed.
- Possible solution: ?

**Comment by pbrier** [comment]
Button was read at several locations in the loop. Now only at top level (and some extra reads discard events on purpose).
