### ISSUE TITLE
Commissioning not effective in 1/10 cases

### ISSUE THREAD

**Issue by diyPresso** [diyPresso/diyPresso-One#9]
In some cases we see that the commissioning is not effective.
software 1.5.0
what do you see: While filling up the boiler the software thinks the water level is constant while it is not
Effect: boiler not full, possible damage to heater, heater only partially under water
Situation: commissioning diyPresso One after build, water reservoir full, user pushed button and level is tarred
What did you expect: that the pump would continue to pump until the boiler is full and the water level is constant
Possible solution: minimum pumping time of 2 minutes / software filtering on load cell / ask user if water is coming from the brew head in the last step of the commissioning process

**Comment by pbrier** [comment]
Fixed by new commisioning prcedure: always pump 30seconds and check if we see water.
Also: there should be a minimum weight decrease of the reservoir after this procedure.
See Issue #12 #14 #15

**Comment by bhulshof** [comment]
Nice fix!
